Currency
purringCatFoundation/ValueObject pull request #11
Opened 2017-03-23 18:45 UTC by adeptofvoltron

![dolarcat](https://cloud.githubusercontent.com/assets/6844275/24264601/3986b90a-1001-11e7-84c0-f01640ff5fd3.gif)

2017-03-23 19:08 UTC, pradzikowski commented
I will handle it... but first 
![106807-grumpy-cat-fuck-gif-imgur-tkeg](https://cloud.githubusercontent.com/assets/1573220/24265497/0df0783c-1004-11e7-9df6-71d76e9f6f30.gif)

2017-03-23 19:10 UTC, adeptofvoltron commented on src/Currency/AbstractCurrency.php
> +        if (!$compare instanceof AbstractCurrency || !$compare instanceof static::class) {
`!$compare instanceof static::class` would be enough, first check mostly for IDE help. let me leave it!! :)

2017-03-23 20:03 UTC, pradzikowski requested changes
Lets start discussion

2017-03-23 20:03 UTC, pradzikowski commented on src/Currency/AbstractCurrency.php
> +
To many lines

2017-03-23 20:03 UTC, pradzikowski commented on src/Currency/Afghani.php
> +
unnecessary line

2017-03-23 20:03 UTC, pradzikowski commented on src/Currency/AbstractCurrency.php
> +    protected $alphabeticCode;
how about set this and numeric code as constants ?

2017-03-23 20:03 UTC, pradzikowski commented on src/Currency/ArgentinePeso.php
> +        $this->numericCode = '32';
I propose use it as public constants.

2017-03-23 20:03 UTC, pradzikowski commented on src/Currency/ArgentinePeso.php
> +        $this->numericCode = '32';
And i propose add unicode symbol code: http://www.fileformat.info/info/unicode/category/Sc/list.htm

2017-03-26 20:35 UTC, pradzikowski requested changes

2017-03-26 20:35 UTC, pradzikowski commented on src/Currency/ArgentinePeso.php
> +    public function __construct($quality)
I think about this topic and IMO you should store inancial info only as int. Because in informatic systems there is [many problems with floats](http://floating-point-gui.de/). Every bank ans financial system store money in Subunit like Grosz or Cent. Ex: 1 USD will be stored as 100 cents. Its much savier.  In this valueObject you forget also about Subunit info.

2017-03-26 20:35 UTC, pradzikowski commented on src/Currency/AbstractCurrency.php
> +    protected $alphabeticCode;
Imho they should be named as isoCode and isoNumCode
https://en.wikipedia.org/wiki/ISO_4217

2017-03-27 09:52 UTC, adeptofvoltron commented on src/Currency/ArgentinePeso.php
> +    public function __construct($quality)
u right. but as you noticed, I get all the currences from external source. And code was generated.
I had no input data about subunits. 
In that case, I will have to search in google for it.
for now I think we can close the topic. and come back to currences later

2017-03-27 12:05 UTC, adeptofvoltron commented
closing. will push changes in another branch

2017-03-27 12:05 UTC, closed without merging