Create gitignore file and basic structure
purringCatFoundation/ValueObject pull request #4
Opened 2017-03-10 12:53 UTC by adeptofvoltron

2017-03-11 21:00 UTC, pradzikowski requested changes

2017-03-11 21:00 UTC, pradzikowski commented on .gitignore
> +# Scala IDE specific (Scala & Java development for Eclipse)
I think we dont need it ....

2017-03-11 21:00 UTC, pradzikowski commented on .gitignore
> +# STS (Spring Tool Suite)
STS is java thing...

2017-03-11 21:00 UTC, pradzikowski commented on .gitignore
> +# Java annotation processor (APT)
Le foo Java !

2017-03-11 21:00 UTC, pradzikowski commented on .gitignore
> +# PyDev specific (Python IDE for Eclipse)
Python @.@

2017-03-11 21:00 UTC, pradzikowski commented on composer.json
> +  "type": "metaapackage",
To much 'a' in this type :)

2017-03-11 21:00 UTC, pradzikowski commented on composer.json
> +  "name": "purring_cat/valueobject",
Imo Name should be the same with namespace. Remember - name is a packages title on packagist.

2017-03-11 21:00 UTC, pradzikowski commented on src/ValueObjectInterface.php
> +     * @return boolean
i suggest add line before return

2017-03-11 21:00 UTC, pradzikowski commented on src/ValueObjectInterface.php
> +}
One line after bracket

2017-03-11 21:00 UTC, pradzikowski commented on src/ValueObjectInterface.php
> +     * @return string
Line before return

2017-03-11 21:02 UTC, adeptofvoltron commented on .gitignore
> +# PyDev specific (Python IDE for Eclipse)
just .gitignore plugin template. does not have any negative affect atm.

2017-03-11 21:02 UTC, adeptofvoltron commented on .gitignore
> +# Java annotation processor (APT)
just .gitignore plugin template. does not have any negative affect atm.

2017-03-11 21:02 UTC, adeptofvoltron commented on .gitignore
> +# STS (Spring Tool Suite)
just .gitignore plugin template. does not have any negative affect atm.

2017-03-11 21:03 UTC, adeptofvoltron commented on .gitignore
> +# Scala IDE specific (Scala & Java development for Eclipse)
just .gitignore plugin template. does not have any negative affect atm.

2017-03-12 13:31 UTC, adeptofvoltron commented on .gitignore
> +# PyDev specific (Python IDE for Eclipse)
deleted

2017-03-12 13:31 UTC, adeptofvoltron commented on .gitignore
> +# Java annotation processor (APT)
deleted

2017-03-12 13:31 UTC, adeptofvoltron commented on .gitignore
> +# STS (Spring Tool Suite)
deleted

2017-03-12 13:31 UTC, adeptofvoltron commented on .gitignore
> +# Scala IDE specific (Scala & Java development for Eclipse)
deleted

2017-03-12 13:32 UTC, adeptofvoltron commented on composer.json
> +  "name": "purring_cat/valueobject",
done

2017-03-12 13:33 UTC, adeptofvoltron commented on src/ValueObjectInterface.php
> +}
done - u [nazi programmer](https://i.imgflip.com/ioemm.jpg)!!

2017-03-12 13:33 UTC, adeptofvoltron commented on src/ValueObjectInterface.php
> +     * @return string
done

2017-03-12 13:34 UTC, adeptofvoltron commented on src/ValueObjectInterface.php
> +     * @return boolean
done

2017-03-12 13:34 UTC, pradzikowski commented on src/ValueObjectInterface.php
> +    public function isEqualTo(ValueObjectInterface $compare): bool ;
Space before semicolon

2017-03-12 13:34 UTC, pradzikowski commented on .gitignore
> +# CDT-specific (C/C++ Development Tooling)
Yo forget cpp ? :D

2017-03-12 13:36 UTC, adeptofvoltron commented on composer.json
> +  "type": "metaapackage",
done

2017-03-12 13:37 UTC, adeptofvoltron commented on .gitignore
> +# CDT-specific (C/C++ Development Tooling)
YAGNI

2017-03-12 13:37 UTC, adeptofvoltron commented on src/ValueObjectInterface.php
> +    public function isEqualTo(ValueObjectInterface $compare): bool ;
done

2017-03-12 13:43 UTC, pradzikowski approved these changes

2017-03-12 13:43 UTC, pradzikowski commented
![image](https://cloud.githubusercontent.com/assets/1573220/23832296/47b5db46-0732-11e7-946a-ef0de836d622.png)

2017-03-12 13:44 UTC, merged