Example Values - Distances - PR created as a place to talk about code structure
purringCatFoundation/ValueObject pull request #6
Opened 2017-03-14 20:59 UTC by adeptofvoltron

2017-03-15 18:13 UTC, pradzikowski requested changes

2017-03-15 18:13 UTC, pradzikowski commented on composer.json
> +  "type": "metcomapackage",
Is it intentional ?

2017-03-15 18:13 UTC, pradzikowski commented on phpunit.xml
> +<?xml version="1.0" encoding="UTF-8"?>
You forgot merge code from PCF to your local fork ?

2017-03-15 18:18 UTC, pradzikowski commented on src/Distance/AbstractDistance.php
> +        $className = get_called_class();
👍

2017-03-15 18:19 UTC, pradzikowski commented on src/Distance/Comparator.php
> +}
Missing line after bracket.

2017-03-15 18:19 UTC, pradzikowski commented on src/Distance/Comparator.php
> +        return $left->isEqualTo($tmpDistance);
missing line before return

2017-03-15 18:20 UTC, pradzikowski commented on src/Distance/Converter.php
> +}
missing line after bracket :P

2017-03-15 19:16 UTC, adeptofvoltron commented
@pradzikowski first start about files structure. Is it ok for you. Or You would rather wish to push all comparators/converters to own directory

2017-03-16 13:59 UTC, adeptofvoltron commented on composer.json
> +  "type": "metcomapackage",
done

2017-03-16 13:59 UTC, adeptofvoltron commented on phpunit.xml
> +<?xml version="1.0" encoding="UTF-8"?>
done

2017-03-16 13:59 UTC, adeptofvoltron commented on src/Distance/AbstractDistance.php
> +        $className = get_called_class();
done

2017-03-16 14:00 UTC, adeptofvoltron commented on src/Distance/Comparator.php
> +}
done

2017-03-16 14:00 UTC, adeptofvoltron commented on src/Distance/Comparator.php
> +        return $left->isEqualTo($tmpDistance);
done

2017-03-16 14:00 UTC, adeptofvoltron commented on src/Distance/Converter.php
> +}
done

2017-03-19 21:36 UTC, pradzikowski commented
@adeptofvoltron there is a conflict.

2017-03-19 21:36 UTC, pradzikowski approved these changes

2017-03-20 18:20 UTC, adeptofvoltron commented
@pradzikowski Done

to  sum-up our speech during PCF meeting. In these repo we will not keep any converters/comparators etc... it is only for VO. All these utils will have their own repo in the future.

2017-03-21 07:24 UTC, merged